<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>  
<div id="footer">
	<dl id="links">
	<%--
			<dt>友情链接：</dt>
			<dd><a href="http://bamao.taobao.com" target="_blank"></a></dd>
			<dd><a href="#" target="_blank">Google</a></dd>
			<dd><a href="#" target="_blank">优酷</a></dd>
			<dd><a href="#" target="_blank">懒人图库</a></dd>
	--%>
	</dl>

	<div id="copyright">
		<script type="text/javascript" src="http://js.tongji.linezing.com/1603674/tongji.js"></script><noscript><a href="http://www.linezing.com"><img src="http://img.tongji.linezing.com/1603674/tongji.gif"/></a></noscript>
		<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F1ed3d54d5bb5bec5412fca954597a53f' type='text/javascript'%3E%3C/script%3E"));
</script>
		&copy; Copyright 2008 - 2010 Jesscool , Inc. All Rights Reserved <a href="mailto:service@jesscool.com">联系我们</a>
	</div>
</div>