<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>  
<div id="footer">
	<dl id="links">
	<!--
			<dt>友情链接：</dt>
			<dd><a href="http://bamao.taobao.com" target="_blank"></a></dd>
			<dd><a href="#" target="_blank">Google</a></dd>
			<dd><a href="#" target="_blank">优酷</a></dd>
			<dd><a href="#" target="_blank">懒人图库</a></dd>
	-->
	</dl>

	<div id="copyright">
		<script type="text/javascript" src="http://js.tongji.linezing.com/1603674/tongji.js"></script><noscript><a href="http://www.linezing.com"><img src="http://img.tongji.linezing.com/1603674/tongji.gif"/></a></noscript>
		&copy; Copyright 2008 - 2010 Jesscool , Inc. All Rights Reserved <a href="mailto:service@jesscool.com">联系我们</a>
	</div>
</div>