<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>  

	<div id="footer">
    	&copy; Copyright 2008 - 2010 Jesscool
    </div>

<script src="http://s.jesscool.com/jspro/jquery-1.4.2.min.js"></script>
<script src="http://s.jesscool.com/jspro/common.js"></script>

<script type="text/javascript" src="http://js.tongji.linezing.com/1603674/tongji.js"></script><noscript><a href="http://www.linezing.com"><img src="http://img.tongji.linezing.com/1603674/tongji.gif"/></a></noscript>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F1ed3d54d5bb5bec5412fca954597a53f' type='text/javascript'%3E%3C/script%3E"));
</script>