<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="Description" content="男士穿衣教程。你的私人形象专家。上jesscool，轻松获得穿衣教程，学习穿衣搭配技巧，衣服是搭出来的。" />
<meta name="Keywords" content="jesscool,男士,男士时尚,男士穿衣教程,男人,男人网,男人装,男人时尚,男性,时尚男人,男生,流行,穿衣教程,时尚,韩国,日本,欧美,穿衣,搭配,帅哥,潮男,型男,造型,形象顾问" />
<link href="http://s.jesscool.com/favicon-rr.ico?ver=3" rel="shortcut icon" type="image/x-icon" />
<script type="text/javascript" src="http://s.jesscool.com/jspro/jquery-1.4.min.js"></script>